### Signup
POST http://localhost:8000/signup/
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword",
  "email": "testuser@example.com"
}

###

### Login
POST http://localhost:8000/login/
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

###

### Test Token
# Replace <TOKEN> with the actual token returned from the login endpoint
GET http://localhost:8000/test_token/
Authorization: Token 9ac8921fdf608e51f6904c7f954ffc8a54b00415
